-- =============================================================================
-- EaseMyOffice CRM — Combined Database Setup
-- Paste this ENTIRE file into your Supabase project's SQL Editor and click RUN.
-- It creates all tables, security policies, roles, and automation.
-- Generated by combining supabase/migrations in order.
-- =============================================================================


-- ─────────────────────────────────────────────────────────────────────────
-- Migration: 20260512095324_b995146d-6172-468d-a72b-47e0bf6602fd.sql
-- ─────────────────────────────────────────────────────────────────────────

-- ============ ENUMS ============
CREATE TYPE public.app_role AS ENUM ('admin','sales','documentation','accounts','renewals','bd');
CREATE TYPE public.lead_stage AS ENUM (
  'new_lead','contacted','interested','documents_pending','quotation_shared',
  'negotiation','payment_pending','payment_received','draft_shared',
  'agreement_signed','completed','renewal_due','lost'
);
CREATE TYPE public.lead_interest AS ENUM ('hot','warm','cold','dead');
CREATE TYPE public.lead_source AS ENUM ('website','email','whatsapp','indiamart','google_ads','meta_ads','referral','direct_call','other');
CREATE TYPE public.service_type AS ENUM ('virtual_office','gst_registration','apob','business_registration','iec','trademark','other');
CREATE TYPE public.followup_status AS ENUM ('pending','done','missed');
CREATE TYPE public.task_priority AS ENUM ('high','medium','low');
CREATE TYPE public.task_status AS ENUM ('todo','in_progress','done');
CREATE TYPE public.activity_type AS ENUM ('note','call','email','whatsapp','stage_change','assignment','followup','created');

-- ============ PROFILES ============
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  email TEXT,
  avatar_url TEXT,
  department TEXT,
  phone TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- ============ USER_ROLES ============
CREATE TABLE public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- has_role security definer
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role public.app_role)
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role);
$$;

CREATE OR REPLACE FUNCTION public.is_admin(_user_id UUID)
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$ SELECT public.has_role(_user_id, 'admin'); $$;

-- Profile auto-create trigger
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  is_first_user BOOLEAN;
BEGIN
  INSERT INTO public.profiles (id, full_name, email)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email,'@',1)), NEW.email);

  -- First user becomes admin, others default to sales
  SELECT NOT EXISTS (SELECT 1 FROM public.user_roles) INTO is_first_user;
  IF is_first_user THEN
    INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'admin');
  ELSE
    INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'sales');
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- updated_at trigger
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;

CREATE TRIGGER profiles_set_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============ LEADS ============
CREATE SEQUENCE public.lead_code_seq START 1001;

CREATE TABLE public.leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_code TEXT NOT NULL UNIQUE DEFAULT ('EMO-' || nextval('public.lead_code_seq')),
  client_name TEXT NOT NULL,
  mobile TEXT NOT NULL,
  alt_mobile TEXT,
  email TEXT,
  company_name TEXT,
  city TEXT,
  state TEXT,
  service_required public.service_type NOT NULL DEFAULT 'virtual_office',
  budget NUMERIC(12,2),
  source public.lead_source NOT NULL DEFAULT 'website',
  assigned_to UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  interest public.lead_interest NOT NULL DEFAULT 'warm',
  score INT NOT NULL DEFAULT 0,
  intent_flags JSONB NOT NULL DEFAULT '{}'::jsonb,
  stage public.lead_stage NOT NULL DEFAULT 'new_lead',
  notes TEXT,
  next_follow_up_at TIMESTAMPTZ,
  last_activity_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX leads_assigned_to_idx ON public.leads(assigned_to);
CREATE INDEX leads_stage_idx ON public.leads(stage);
CREATE INDEX leads_interest_idx ON public.leads(interest);
CREATE INDEX leads_next_follow_up_idx ON public.leads(next_follow_up_at);
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER leads_set_updated_at BEFORE UPDATE ON public.leads
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============ FOLLOW UPS ============
CREATE TABLE public.follow_ups (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id UUID NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  due_at TIMESTAMPTZ NOT NULL,
  action TEXT NOT NULL,
  status public.followup_status NOT NULL DEFAULT 'pending',
  completed_at TIMESTAMPTZ,
  note TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX follow_ups_lead_idx ON public.follow_ups(lead_id);
CREATE INDEX follow_ups_owner_idx ON public.follow_ups(owner_id);
CREATE INDEX follow_ups_status_due_idx ON public.follow_ups(status, due_at);
ALTER TABLE public.follow_ups ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER follow_ups_set_updated_at BEFORE UPDATE ON public.follow_ups
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Sync next_follow_up_at on leads when follow_ups change
CREATE OR REPLACE FUNCTION public.sync_lead_next_followup()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_lead UUID;
BEGIN
  v_lead := COALESCE(NEW.lead_id, OLD.lead_id);
  UPDATE public.leads
    SET next_follow_up_at = (
      SELECT MIN(due_at) FROM public.follow_ups
      WHERE lead_id = v_lead AND status = 'pending'
    ),
    last_activity_at = now()
  WHERE id = v_lead;
  RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER follow_ups_sync_lead
  AFTER INSERT OR UPDATE OR DELETE ON public.follow_ups
  FOR EACH ROW EXECUTE FUNCTION public.sync_lead_next_followup();

-- ============ TASKS ============
CREATE TABLE public.tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  lead_id UUID REFERENCES public.leads(id) ON DELETE SET NULL,
  priority public.task_priority NOT NULL DEFAULT 'medium',
  status public.task_status NOT NULL DEFAULT 'todo',
  due_at TIMESTAMPTZ,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER tasks_set_updated_at BEFORE UPDATE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============ LEAD ACTIVITIES (timeline) ============
CREATE TABLE public.lead_activities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id UUID NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  actor_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  type public.activity_type NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX lead_activities_lead_idx ON public.lead_activities(lead_id, created_at DESC);
ALTER TABLE public.lead_activities ENABLE ROW LEVEL SECURITY;

-- ============ RLS POLICIES ============

-- profiles: everyone authenticated reads; users update own; admins update any
CREATE POLICY "profiles_select_all" ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE TO authenticated
  USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "profiles_admin_update" ON public.profiles FOR UPDATE TO authenticated
  USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

-- user_roles: users see own roles; admins manage
CREATE POLICY "user_roles_select_own" ON public.user_roles FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.is_admin(auth.uid()));
CREATE POLICY "user_roles_admin_all" ON public.user_roles FOR ALL TO authenticated
  USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

-- leads
-- Read: admin sees all; sales sees own assigned; other depts see all (for cross-team workflow)
CREATE POLICY "leads_select" ON public.leads FOR SELECT TO authenticated
  USING (
    public.is_admin(auth.uid())
    OR assigned_to = auth.uid()
    OR created_by = auth.uid()
    OR public.has_role(auth.uid(),'documentation')
    OR public.has_role(auth.uid(),'accounts')
    OR public.has_role(auth.uid(),'renewals')
    OR public.has_role(auth.uid(),'bd')
  );
CREATE POLICY "leads_insert" ON public.leads FOR INSERT TO authenticated
  WITH CHECK (
    public.is_admin(auth.uid())
    OR public.has_role(auth.uid(),'sales')
    OR public.has_role(auth.uid(),'bd')
  );
CREATE POLICY "leads_update" ON public.leads FOR UPDATE TO authenticated
  USING (
    public.is_admin(auth.uid())
    OR assigned_to = auth.uid()
    OR public.has_role(auth.uid(),'documentation')
    OR public.has_role(auth.uid(),'accounts')
    OR public.has_role(auth.uid(),'renewals')
  ) WITH CHECK (
    public.is_admin(auth.uid())
    OR assigned_to = auth.uid()
    OR public.has_role(auth.uid(),'documentation')
    OR public.has_role(auth.uid(),'accounts')
    OR public.has_role(auth.uid(),'renewals')
  );
CREATE POLICY "leads_delete_admin" ON public.leads FOR DELETE TO authenticated
  USING (public.is_admin(auth.uid()));

-- follow_ups: same access as parent lead (simplified: owner or admin or assignee of lead)
CREATE POLICY "followups_select" ON public.follow_ups FOR SELECT TO authenticated
  USING (
    public.is_admin(auth.uid())
    OR owner_id = auth.uid()
    OR EXISTS (SELECT 1 FROM public.leads l WHERE l.id = lead_id AND (l.assigned_to = auth.uid() OR l.created_by = auth.uid()))
  );
CREATE POLICY "followups_insert" ON public.follow_ups FOR INSERT TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "followups_update" ON public.follow_ups FOR UPDATE TO authenticated
  USING (
    public.is_admin(auth.uid()) OR owner_id = auth.uid()
    OR EXISTS (SELECT 1 FROM public.leads l WHERE l.id = lead_id AND l.assigned_to = auth.uid())
  ) WITH CHECK (true);
CREATE POLICY "followups_delete" ON public.follow_ups FOR DELETE TO authenticated
  USING (public.is_admin(auth.uid()) OR owner_id = auth.uid());

-- tasks: own tasks or admin
CREATE POLICY "tasks_select" ON public.tasks FOR SELECT TO authenticated
  USING (public.is_admin(auth.uid()) OR owner_id = auth.uid() OR created_by = auth.uid());
CREATE POLICY "tasks_insert" ON public.tasks FOR INSERT TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "tasks_update" ON public.tasks FOR UPDATE TO authenticated
  USING (public.is_admin(auth.uid()) OR owner_id = auth.uid() OR created_by = auth.uid())
  WITH CHECK (true);
CREATE POLICY "tasks_delete" ON public.tasks FOR DELETE TO authenticated
  USING (public.is_admin(auth.uid()) OR owner_id = auth.uid() OR created_by = auth.uid());

-- lead_activities: read if can read parent lead; insert by anyone authenticated (actor logging)
CREATE POLICY "activities_select" ON public.lead_activities FOR SELECT TO authenticated
  USING (
    public.is_admin(auth.uid())
    OR EXISTS (SELECT 1 FROM public.leads l WHERE l.id = lead_id AND (
      l.assigned_to = auth.uid() OR l.created_by = auth.uid()
      OR public.has_role(auth.uid(),'documentation')
      OR public.has_role(auth.uid(),'accounts')
      OR public.has_role(auth.uid(),'renewals')
      OR public.has_role(auth.uid(),'bd')
    ))
  );
CREATE POLICY "activities_insert" ON public.lead_activities FOR INSERT TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL);


-- ─────────────────────────────────────────────────────────────────────────
-- Migration: 20260512100918_20c29cef-2237-4ee0-8f61-2f2e5abc35a0.sql
-- ─────────────────────────────────────────────────────────────────────────
-- Report subscriptions for scheduled email delivery
CREATE TABLE public.report_subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL,
  reports TEXT[] NOT NULL DEFAULT ARRAY['overdue','pipeline','productivity']::TEXT[],
  frequency TEXT NOT NULL DEFAULT 'daily' CHECK (frequency IN ('daily','weekly')),
  enabled BOOLEAN NOT NULL DEFAULT true,
  last_sent_at TIMESTAMPTZ,
  created_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.report_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "subs_admin_all" ON public.report_subscriptions
  FOR ALL TO authenticated
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

CREATE TRIGGER subs_updated_at
  BEFORE UPDATE ON public.report_subscriptions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX idx_report_subs_enabled ON public.report_subscriptions(enabled, frequency);

-- ─────────────────────────────────────────────────────────────────────────
-- Migration: 20260512101621_6f65d6e8-b695-47de-b869-42e094c3f6d3.sql
-- ─────────────────────────────────────────────────────────────────────────
-- Auto-create profile + grant admin role for every new signup (demo/preview mode)
CREATE OR REPLACE FUNCTION public.handle_new_user_demo()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1))
  )
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'admin')
  ON CONFLICT DO NOTHING;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created_demo ON auth.users;
CREATE TRIGGER on_auth_user_created_demo
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_demo();

-- Promote any existing users to admin too
INSERT INTO public.user_roles (user_id, role)
SELECT id, 'admin' FROM auth.users
ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────
-- Migration: 20260512102728_f94d1644-24e4-4c9d-9fbf-bac1635d4706.sql
-- ─────────────────────────────────────────────────────────────────────────
-- 1) Enable realtime
ALTER TABLE public.leads REPLICA IDENTITY FULL;
ALTER TABLE public.follow_ups REPLICA IDENTITY FULL;
ALTER TABLE public.lead_activities REPLICA IDENTITY FULL;

DO $$
BEGIN
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.leads; EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.follow_ups; EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.lead_activities; EXCEPTION WHEN duplicate_object THEN NULL; END;
END $$;

-- 2) Admin-only clear
CREATE OR REPLACE FUNCTION public.clear_demo_data()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'Only admins can clear demo data';
  END IF;
  DELETE FROM public.lead_activities;
  DELETE FROM public.follow_ups;
  DELETE FROM public.leads;
END;
$$;

REVOKE ALL ON FUNCTION public.clear_demo_data() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.clear_demo_data() TO authenticated;

-- 3) Admin-only reseed (100 varied leads + multi follow-ups + activity logs)
CREATE OR REPLACE FUNCTION public.seed_demo_leads()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_owner uuid;
  v_count integer := 0;
  v_lead record;
BEGIN
  IF NOT public.is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'Only admins can seed demo data';
  END IF;

  v_owner := auth.uid();

  -- Insert 100 leads
  WITH seed AS (
    SELECT
      g AS n,
      (ARRAY['Aarav Sharma','Vivaan Iyer','Aditya Mehta','Vihaan Reddy','Arjun Khanna','Sai Patel','Reyansh Gupta','Krishna Nair','Ishaan Kapoor','Shaurya Joshi',
             'Atharv Singh','Advik Rao','Kabir Bhatia','Anaya Verma','Diya Malhotra','Saanvi Desai','Aadhya Pillai','Myra Chopra','Aaradhya Menon','Ira Jain',
             'Pari Bose','Anika Dutta','Navya Saxena','Riya Agarwal','Kiara Shetty','Rohan Trivedi','Yash Bhatt','Dev Chauhan','Aryan Mishra','Karthik Subramanian'])[1+(g % 30)] AS client,
      (ARRAY['Acme Ventures','Bluestone Labs','Crayon Retail','Dovetail Tech','Evershine Exports','Fintrek Capital','Globe Logistics','Helix Pharma','Indus Foods','Jasper Studio',
             'Kavya Apparel','Luminate AI','Mosaic Health','Nimbus Cloud','Orbit Mobility','Pivotal CRM','Quartz Realty','Ridgeline Auto','Sandstorm Media','Tessera Bio'])[1+(g % 20)] AS company,
      (ARRAY['Bengaluru','Mumbai','Delhi','Hyderabad','Pune','Chennai','Gurgaon','Noida','Ahmedabad','Kolkata'])[1+(g % 10)] AS city,
      (ARRAY['Karnataka','Maharashtra','Delhi','Telangana','Maharashtra','Tamil Nadu','Haryana','Uttar Pradesh','Gujarat','West Bengal'])[1+(g % 10)] AS st,
      (ARRAY['virtual_office','gst_registration','apob','business_registration','iec','trademark','other'])[1+(g % 7)]::service_type AS svc,
      (ARRAY['website','email','whatsapp','indiamart','google_ads','meta_ads','referral','direct_call'])[1+(g % 8)]::lead_source AS src,
      (ARRAY['hot','warm','cold','warm','hot','warm','cold','dead'])[1+(g % 8)]::lead_interest AS intr,
      (ARRAY['new_lead','contacted','interested','documents_pending','quotation_shared','negotiation','payment_pending','payment_received','draft_shared','agreement_signed','completed','renewal_due','lost'])[1+(g % 13)]::lead_stage AS stg,
      (5000 + (g*137 % 45000))::numeric AS budget
    FROM generate_series(1,100) g
  )
  INSERT INTO public.leads
    (client_name, company_name, mobile, alt_mobile, email, city, state, service_required, source, interest, stage, budget,
     assigned_to, created_by, score, intent_flags, notes, next_follow_up_at, last_activity_at, created_at, updated_at)
  SELECT
    client, company,
    '+9198' || lpad((10000000 + n*7919 % 89999999)::text, 8, '0'),
    CASE WHEN n % 4 = 0 THEN '+9197' || lpad((20000000 + n*3517 % 79999999)::text, 8, '0') ELSE NULL END,
    lower(replace(client,' ','.')) || n || '@' || lower(replace(company,' ','')) || '.com',
    city, st, svc, src, intr, stg, budget,
    v_owner, v_owner,
    (n*13 % 100),
    jsonb_build_object('asked_pricing',(n%2=0),'asked_agreement',(n%5=0),'asked_documents',(n%3=0),'ready_for_payment',(n%7=0),'requested_callback',(n%4=0)),
    CASE WHEN n%3=0 THEN 'Client requested callback after 5 PM. Follow up needed.'
         WHEN n%3=1 THEN 'Sent quotation. Awaiting confirmation on pricing.'
         ELSE 'Initial discussion done. Documents shared via email.' END,
    CASE
      WHEN stg IN ('completed','lost') THEN NULL
      WHEN n%4=0 THEN now() - ((n%6+1)||' days')::interval
      WHEN n%4=1 THEN now() + ((n%8)||' hours')::interval
      ELSE now() + ((n%14+1)||' days')::interval
    END,
    now() - ((n%10)||' days')::interval,
    now() - ((n%30)||' days')::interval,
    now() - ((n%30)||' days')::interval
  FROM seed;

  GET DIAGNOSTICS v_count = ROW_COUNT;

  -- 1-3 follow-ups per lead with varied schedules
  FOR v_lead IN SELECT id, assigned_to, created_by, stage FROM public.leads LOOP
    INSERT INTO public.follow_ups (lead_id, owner_id, action, due_at, status, created_by, note)
    SELECT
      v_lead.id, v_lead.assigned_to,
      (ARRAY['Call to confirm pricing','Send quotation PDF','Share documents checklist','Schedule meeting','Confirm payment receipt','Send agreement draft','Welcome call','Renewal reminder','WhatsApp pricing','Email proposal'])[1 + (abs(hashtext(v_lead.id::text || k::text)) % 10)],
      CASE k
        WHEN 0 THEN now() + ((abs(hashtext(v_lead.id::text)) % 48) - 24 || ' hours')::interval
        WHEN 1 THEN now() + ((abs(hashtext(v_lead.id::text)) % 7 + 1) || ' days')::interval
        ELSE now() + ((abs(hashtext(v_lead.id::text)) % 21 + 7) || ' days')::interval
      END,
      CASE WHEN v_lead.stage IN ('completed','lost') AND k = 0 THEN 'completed'::followup_status ELSE 'pending'::followup_status END,
      v_lead.created_by,
      (ARRAY['Auto-generated reminder','Awaiting client response','Priority follow-up','Decision pending','Routine check-in'])[1 + (abs(hashtext(v_lead.id::text || k::text)) % 5)]
    FROM generate_series(0, 1 + abs(hashtext(v_lead.id::text)) % 3) k;

    -- 2-5 activity / communication log entries per lead
    INSERT INTO public.lead_activities (lead_id, actor_id, type, title, body, payload, created_at)
    SELECT
      v_lead.id, v_lead.assigned_to,
      (ARRAY['call_logged','email_sent','whatsapp_sent','note_added','stage_changed']::activity_type[])[1 + (abs(hashtext(v_lead.id::text || k::text)) % 5)],
      (ARRAY['Outbound call','Quotation email','WhatsApp message','Internal note','Stage updated'])[1 + (abs(hashtext(v_lead.id::text || k::text)) % 5)],
      (ARRAY['Discussed pricing and timelines. Will share quote.',
             'Sent quotation with detailed breakdown.',
             'Shared agreement draft on WhatsApp.',
             'Client busy this week, retry next Monday.',
             'Moved to negotiation stage.'])[1 + (abs(hashtext(v_lead.id::text || k::text)) % 5)],
      jsonb_build_object('duration_sec', 60 + abs(hashtext(v_lead.id::text||k::text)) % 600),
      now() - ((abs(hashtext(v_lead.id::text||k::text)) % 30) || ' days')::interval
    FROM generate_series(0, 1 + abs(hashtext(v_lead.id::text)) % 4) k;
  END LOOP;

  RETURN v_count;
END;
$$;

REVOKE ALL ON FUNCTION public.seed_demo_leads() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.seed_demo_leads() TO authenticated;

-- ─────────────────────────────────────────────────────────────────────────
-- Migration: 20260512110259_34240e6f-b5cb-4327-b981-225e0e50e6b6.sql
-- ─────────────────────────────────────────────────────────────────────────
-- Enable Supabase realtime for the dashboard tables
ALTER TABLE public.leads REPLICA IDENTITY FULL;
ALTER TABLE public.follow_ups REPLICA IDENTITY FULL;
ALTER TABLE public.lead_activities REPLICA IDENTITY FULL;

DO $$
BEGIN
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.leads; EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.follow_ups; EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.lead_activities; EXCEPTION WHEN duplicate_object THEN NULL; END;
END$$;

-- Per-user notification preferences for follow-up reminders
CREATE TABLE IF NOT EXISTS public.notification_prefs (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  in_app_enabled boolean NOT NULL DEFAULT true,
  email_enabled boolean NOT NULL DEFAULT false,
  remind_minutes_before integer NOT NULL DEFAULT 15,
  daily_digest boolean NOT NULL DEFAULT false,
  email_address text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.notification_prefs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "notif_prefs_select_own" ON public.notification_prefs
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "notif_prefs_insert_own" ON public.notification_prefs
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "notif_prefs_update_own" ON public.notification_prefs
  FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "notif_prefs_delete_own" ON public.notification_prefs
  FOR DELETE TO authenticated USING (user_id = auth.uid());

CREATE TRIGGER notif_prefs_set_updated_at
  BEFORE UPDATE ON public.notification_prefs
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ─────────────────────────────────────────────────────────────────────────
-- Migration: 20260512132548_934912a2-0ef2-48a6-baa6-7f2cbf9c6272.sql
-- ─────────────────────────────────────────────────────────────────────────
-- KPI tile click events: server-side store so the admin report can aggregate
-- across all devices/users.
CREATE TABLE IF NOT EXISTS public.kpi_events (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  team TEXT,
  kpi_id TEXT NOT NULL,
  label TEXT,
  path TEXT,
  search JSONB NOT NULL DEFAULT '{}'::jsonb,
  value NUMERIC,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS kpi_events_created_idx ON public.kpi_events (created_at DESC);
CREATE INDEX IF NOT EXISTS kpi_events_kpi_idx ON public.kpi_events (kpi_id);
CREATE INDEX IF NOT EXISTS kpi_events_user_idx ON public.kpi_events (user_id);
CREATE INDEX IF NOT EXISTS kpi_events_team_idx ON public.kpi_events (team);

ALTER TABLE public.kpi_events ENABLE ROW LEVEL SECURITY;

-- Any authenticated user can record their own KPI clicks.
CREATE POLICY "kpi_events_insert_own"
  ON public.kpi_events FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Only admins can read aggregated KPI usage.
CREATE POLICY "kpi_events_admin_select"
  ON public.kpi_events FOR SELECT
  TO authenticated
  USING (public.is_admin(auth.uid()));

-- Only admins can purge events (e.g. clear button).
CREATE POLICY "kpi_events_admin_delete"
  ON public.kpi_events FOR DELETE
  TO authenticated
  USING (public.is_admin(auth.uid()));

-- ─────────────────────────────────────────────────────────────────────────
-- Migration: 20260513063631_f2ead7b1-3310-48a9-a5ff-b48f4d690fa5.sql
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE public.app_settings (
  key text PRIMARY KEY,
  value jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid
);

ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "app_settings_admin_select" ON public.app_settings
  FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));

CREATE POLICY "app_settings_admin_insert" ON public.app_settings
  FOR INSERT TO authenticated WITH CHECK (public.is_admin(auth.uid()));

CREATE POLICY "app_settings_admin_update" ON public.app_settings
  FOR UPDATE TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

CREATE POLICY "app_settings_admin_delete" ON public.app_settings
  FOR DELETE TO authenticated USING (public.is_admin(auth.uid()));

CREATE TRIGGER app_settings_set_updated_at
  BEFORE UPDATE ON public.app_settings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ─────────────────────────────────────────────────────────────────────────
-- Migration: 20260513065703_e3d6d99b-b29d-4ba9-85eb-229d576142b6.sql
-- ─────────────────────────────────────────────────────────────────────────

CREATE SEQUENCE IF NOT EXISTS public.booking_code_seq START 1001;

CREATE TABLE IF NOT EXISTS public.bookings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_code text NOT NULL UNIQUE DEFAULT ('EMO-BK-' || nextval('public.booking_code_seq')),
  external_booking_id text,
  booking_date date NOT NULL DEFAULT CURRENT_DATE,
  sales_agent_id uuid,
  sales_agent_name text NOT NULL,
  booking_source text NOT NULL DEFAULT 'Website',
  plan_name text NOT NULL,
  vo_plan text DEFAULT '',
  sp_name text DEFAULT '',
  area text DEFAULT '',
  city text DEFAULT '',
  state text DEFAULT '',
  sp_status text DEFAULT 'Active',
  vo_amount numeric NOT NULL DEFAULT 0,
  vo_gst numeric NOT NULL DEFAULT 0,
  addon_services text DEFAULT '',
  addon_amount numeric NOT NULL DEFAULT 0,
  addon_gst numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  tds_pct numeric NOT NULL DEFAULT 0,
  tds_amount numeric NOT NULL DEFAULT 0,
  amount_after_tds numeric NOT NULL DEFAULT 0,
  payment_mode_ref text DEFAULT '',
  payment_id_utr text DEFAULT '',
  invoice_number text DEFAULT '',
  sp_payable numeric NOT NULL DEFAULT 0,
  addon_payable numeric NOT NULL DEFAULT 0,
  profit numeric NOT NULL DEFAULT 0,
  sp_payment_status text NOT NULL DEFAULT 'Pending',
  vo_status text NOT NULL DEFAULT 'Pending',
  business_name text DEFAULT '',
  client_name text NOT NULL,
  email_id text DEFAULT '',
  contact_no text NOT NULL,
  remarks text DEFAULT '',
  sales_month text DEFAULT '',
  -- partial payment tracking
  amount_received numeric NOT NULL DEFAULT 0,
  balance_amount numeric NOT NULL DEFAULT 0,
  balance_due_date date,
  balance_paid_at timestamptz,
  last_reminder_sent_at timestamptz,
  -- ownership
  assigned_to uuid,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bookings_created_by ON public.bookings(created_by);
CREATE INDEX IF NOT EXISTS idx_bookings_assigned_to ON public.bookings(assigned_to);
CREATE INDEX IF NOT EXISTS idx_bookings_balance_due ON public.bookings(balance_due_date) WHERE balance_paid_at IS NULL AND balance_amount > 0;

CREATE TRIGGER trg_bookings_updated_at
BEFORE UPDATE ON public.bookings
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

CREATE POLICY bookings_select ON public.bookings
FOR SELECT TO authenticated
USING (
  public.is_admin(auth.uid())
  OR assigned_to = auth.uid()
  OR created_by = auth.uid()
  OR public.has_role(auth.uid(), 'accounts')
  OR public.has_role(auth.uid(), 'documentation')
);

CREATE POLICY bookings_insert ON public.bookings
FOR INSERT TO authenticated
WITH CHECK (
  public.is_admin(auth.uid())
  OR public.has_role(auth.uid(), 'sales')
  OR public.has_role(auth.uid(), 'bd')
);

CREATE POLICY bookings_update ON public.bookings
FOR UPDATE TO authenticated
USING (
  public.is_admin(auth.uid())
  OR assigned_to = auth.uid()
  OR created_by = auth.uid()
  OR public.has_role(auth.uid(), 'accounts')
)
WITH CHECK (
  public.is_admin(auth.uid())
  OR assigned_to = auth.uid()
  OR created_by = auth.uid()
  OR public.has_role(auth.uid(), 'accounts')
);

CREATE POLICY bookings_delete ON public.bookings
FOR DELETE TO authenticated
USING (public.is_admin(auth.uid()));


-- ─────────────────────────────────────────────────────────────────────────
-- Migration: 20260513075203_88683274-a7ff-404e-8f6c-345f31bbebd4.sql
-- ─────────────────────────────────────────────────────────────────────────

-- User-level theme/appearance preferences (synced across devices)
CREATE TABLE public.user_theme_prefs (
  user_id uuid PRIMARY KEY,
  prefs jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.user_theme_prefs ENABLE ROW LEVEL SECURITY;

CREATE POLICY user_theme_prefs_select_own ON public.user_theme_prefs
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY user_theme_prefs_upsert_own ON public.user_theme_prefs
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY user_theme_prefs_update_own ON public.user_theme_prefs
  FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY user_theme_prefs_delete_own ON public.user_theme_prefs
  FOR DELETE TO authenticated USING (user_id = auth.uid());

-- Allow any authenticated user to read the org-wide default theme.
-- (app_settings already restricts admin-only writes via existing policies.)
CREATE POLICY app_settings_read_org_theme ON public.app_settings
  FOR SELECT TO authenticated USING (key = 'org.theme_default');


-- ─────────────────────────────────────────────────────────────────────────
-- Migration: 20260513092807_f2883781-b05c-487b-9922-db5b142fc3a3.sql
-- ─────────────────────────────────────────────────────────────────────────
-- Hot filters on leads
CREATE INDEX IF NOT EXISTS idx_leads_stage ON public.leads (stage);
CREATE INDEX IF NOT EXISTS idx_leads_interest ON public.leads (interest);
CREATE INDEX IF NOT EXISTS idx_leads_next_follow_up_at ON public.leads (next_follow_up_at) WHERE next_follow_up_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_leads_assigned_to ON public.leads (assigned_to);
CREATE INDEX IF NOT EXISTS idx_leads_created_by ON public.leads (created_by);
CREATE INDEX IF NOT EXISTS idx_leads_created_at_desc ON public.leads (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_last_activity_at_desc ON public.leads (last_activity_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_updated_at ON public.leads (updated_at);
CREATE INDEX IF NOT EXISTS idx_leads_service_required ON public.leads (service_required);
-- Composite for "needs attention" / pipeline mobile filter
CREATE INDEX IF NOT EXISTS idx_leads_stage_next_followup ON public.leads (stage, next_follow_up_at);

-- Hot filters on follow_ups
CREATE INDEX IF NOT EXISTS idx_followups_lead_id ON public.follow_ups (lead_id);
CREATE INDEX IF NOT EXISTS idx_followups_owner_id ON public.follow_ups (owner_id);
CREATE INDEX IF NOT EXISTS idx_followups_status_due_at ON public.follow_ups (status, due_at);
CREATE INDEX IF NOT EXISTS idx_followups_due_at ON public.follow_ups (due_at);
CREATE INDEX IF NOT EXISTS idx_followups_updated_at ON public.follow_ups (updated_at);

-- Activity feed
CREATE INDEX IF NOT EXISTS idx_lead_activities_created_at_desc ON public.lead_activities (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lead_activities_lead_id ON public.lead_activities (lead_id);

-- Bookings filters
CREATE INDEX IF NOT EXISTS idx_bookings_assigned_to ON public.bookings (assigned_to);
CREATE INDEX IF NOT EXISTS idx_bookings_created_by ON public.bookings (created_by);
CREATE INDEX IF NOT EXISTS idx_bookings_balance_due_date ON public.bookings (balance_due_date) WHERE balance_due_date IS NOT NULL;
